### ISSUE TITLE
The game does not start on Archlinux

### ISSUE THREAD

**Issue by jean553** [jean553/rust-breakout#28]
Error output: Couldn\'t find any pixel format that matches the criterias.

This is a known issue, reported here on piston_window: https://github.com/PistonDevelopers/piston/issues/1202

This is due to my version of Mesa:
```
glxinfo | grep 'OpenGL version'
OpenGL version string: 3.0 Mesa 17.2.2
```

I have to check on Ubuntu 16.04 if the problem occurs.

**Comment by jean553** [comment]
Tested on Ubuntu 14.04, it works correctly.

**Comment by eisterman** [comment]
On ArchLinux the solution at the moment is downgrade Mesa:
`sudo pacman -U https://archive.archlinux.org/packages/m/mesa/mesa-17.1.0-1-x86_64.pkg.tar.xz`

Ref: https://github.com/PistonDevelopers/piston/issues/1202#issuecomment-353432955

**Comment by Cxarli** [comment]
This seems to have been fixed with the latest `mesa 18.*`. See https://github.com/PistonDevelopers/piston/issues/1202 for more information.

**Comment by jean553** [comment]
Exact. Problem solved with `mesa 18.*`. Thanks.
